os: linux
dist: xenial
language: php
jobs:
  include:
    - dist: xenial
      php: '5.6'
    - dist: xenial
      php: '7.0'
    - dist: xenial
      php: '7.1'
    - dist: xenial
      php: '7.2'
    - dist: xenial
      php: '7.3'
    - dist: focal
      php: '7.4'
    - dist: focal
      php: '8.0'
    - dist: focal
      php: '8.1.0'

cache:
  directories:
    - .autoconf
    - $HOME/.m2

before_script:
  - composer install --prefer-dist

script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "8.0" ]]; then XDEBUG_MODE=coverage vendor/bin/phpunit --testdox --coverage-clover coverage.xml -- tests; else php vendor/bin/phpunit --testdox -- tests; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
