<?php
declare(strict_types=1);
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2017-2020 Michael Dekker (https://github.com/firstred)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
 * is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * @author    Michael Dekker <git@michaeldekker.nl>
 *
 * @copyright 2017-2020 Michael Dekker
 *
 * @license   https://opensource.org/licenses/MIT The MIT License
 */

namespace Firstred\PostNL\Entity;

use Firstred\PostNL\Exception\InvalidArgumentException;
use Firstred\PostNL\Misc\ValidateAndFix;

/**
 * Class Shipment
 */
class Shipment extends AbstractEntity
{
    /**
     * Addresses
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @var Address[]|null $address
     *
     * @since   1.0.0
     */
    protected $address;

    /**
     * Addresses
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @var Address[]|null $addresses
     *
     * @since   1.0.0
     */
    protected $addresses;

    /**
     * Amounts
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @var Amount[]|null $amounts
     *
     * @since   1.0.0
     */
    protected $amounts;

    /**
     * Main barcode
     *
     * @pattern ^.{1,35}$
     *
     * @example 3SDEVC2016112104
     *
     * @var string|null $barcode
     *
     * @since   1.0.0
     */
    protected $mainBarcode;

    /**
     * Barcode
     *
     * @pattern ^.{1,35}$
     *
     * @example 3SDEVC2016112104
     *
     * @var string|null $barcode
     *
     * @since   1.0.0
     */
    protected $barcode;

    /**
     * Code used for logistic purposes (usually generated by the service itself when needed)
     *
     * @pattern ^.{0,35}$
     *
     * @example #2426A3A#03#0306#
     *
     * @var string|null $codingText
     *
     * @since   1.0.0
     */
    protected $codingText;

    /**
     * Ending date/time of the collection of the shipment. Format: d-m-Y H:i:s
     *
     * @pattern ^(?:0[1-9]|[1-2][0-9]|3[0-1])-(?:0[1-9]|1[0-2])-[0-9]{4}\s(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$
     *
     * @example 03-07-2019 17:00:00
     *
     * @var string|null $collectionTimeStampEnd
     *
     * @since   1.0.0
     */
    protected $collectionTimeStampEnd;

    /**
     * Starting date/time of the collection of the shipment. Format: d-m-Y H:i:s
     *
     * @pattern ^(?:0[1-9]|[1-2][0-9]|3[0-1])-(?:0[1-9]|1[0-2])-[0-9]{4}\s(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$
     *
     * @example 03-07-2019 16:00:00
     *
     * @var string|null $collectionTimeStampStart
     *
     * @since   1.0.0
     */
    protected $collectionTimeStampStart;

    /**
     * One or more Contact elements belonging to a shipment. Mandatory in some cases. Please refer to the Guidelines.
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @var Contact[]|null $contacts
     *
     * @since   1.0.0
     */
    protected $contacts;

    /**
     * Content of the shipment. Mandatory for Extra@Home shipments
     *
     * @pattern ^.{0,35}$
     *
     * @example Media player
     *
     * @var string|null $content
     *
     * @since   1.0.0
     */
    protected $content;

    /**
     * Cost center of the shipment.
     * This value will appear on your invoice.
     *
     * @pattern ^.{0,35}$
     *
     * @example SX-GT-66
     *
     * @var string|null $costCenter
     *
     * @since   1.0.0
     */
    protected $costCenter;

    /**
     * Customer
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @var Customer|null $customer
     *
     * @since   2.0.0
     */
    protected $customer;

    /**
     * Order number of the customer.
     *
     * @pattern ^.{0,35}$
     *
     * @example 8689242390
     *
     * @var string|null $customerOrderNumber
     *
     * @since   1.0.0
     */
    protected $customerOrderNumber;

    /**
     * The Customs type is mandatory for GlobalPack shipments and not allowed for any other shipment types.
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @var Customs|null $customs
     *
     * @since   1.0.0
     */
    protected $customs;

    /**
     * Delivery address type
     *
     * @pattern pattern: ^\d{2}$
     *
     * @example 09
     *
     * @var string|null $deliveryAddress
     *
     * @since   1.0.0
     */
    protected $deliveryAddress;

    /**
     * The delivery date and the specific starting time of the shipment delivery. This can be retrieved from the DeliveryDate webservice using the MyTime delivery option. Format: d-m-Y H:i:s
     *
     * @pattern ^(?:[0-3]\d-[01]\d-[12]\d{3}\s+)[0-2]\d:[0-5]\d(?:[0-5]\d)$
     *
     * @example 03-07-2019 14:30:00
     *
     * @var string|null $deliveryTimeStampStart
     *
     * @since   1.0.0
     */
    protected $deliveryTimeStampStart;

    /**
     * The delivery date and the specific end time of the shipment delivery. This can be retrieved from the DeliveryDate webservice using the MyTime delivery option. Format: d-m-Y H:i:s
     *
     * @pattern ^(?:[0-3]\d-[01]\d-[12]\d{3}\s+)[0-2]\d:[0-5]\d(?:[0-5]\d)$
     *
     * @example 03-07-2019 16:30:00
     *
     * @var string|null $deliveryTimeStampEnd
     *
     * @since   1.0.0
     */
    protected $deliveryTimeStampEnd;

    /**
     * The delivery date of the shipment. We strongly advice to use the DeliveryDate service to get this date when using delivery options like Evening/Morning/Sameday delivery etc. For those
     * products, this field is mandatory (please regard the Guidelines section). Format: d-m-Y H:i:s
     *
     * @pattern ^(?:0[1-9]|[1-2][0-9]|3[0-1])-(?:0[1-9]|1[0-2])-[0-9]{4}\s(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$
     *
     * @example 03-07-2019 14:00:00
     *
     * @var string|null $deliveryDate
     *
     * @since   1.0.0
     */
    protected $deliveryDate;

    /**
     * Dimension
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @var Dimension|null $dimension
     *
     * @since   1.0.0
     */
    protected $dimension;

    /**
     * GenerateBarcodeRequest of the downstream network partner of PostNL Pakketten.
     * Madatory for requesting GlobalPack combilabel product codes
     *
     * @pattern ^.{0,35}$
     *
     * @example CD123456785NL
     *
     * @var string|null $downPartnerBarcode
     *
     * @since   1.0.0
     */
    protected $downPartnerBarcode;

    /**
     * Identification of the downstream network partner of PostNL Pakketten.
     * Mandatory for Pickup at PostNl Location Belgium. Use the data from the Location API response; attribute RetailNetworkID
     *
     * @pattern ^.{0,35}$
     *
     * @example LD-01
     *
     * @var string|null $downPartnerID
     *
     * @since   1.0.0
     */
    protected $downPartnerID;

    /**
     * Identification of the location of the downstream network partner of PostNL Pakketten.
     *
     * @pattern ^.{0,10}$
     *
     * @example BE0Q82
     *
     * @var string|null $downPartnerLocation
     *
     * @since   1.0.0
     */
    protected $downPartnerLocation;

    /**
     * List of 0 or more Group types with data, grouping multiple shipments together.
     * Mandatory for multicollo shipments. Please see Guidelines (Multiple shipments) for more information.
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @var Group[]|null $groups
     *
     * @since   1.0.0
     */
    protected $groups;

    /**
     * Expiration date of the ID document.
     * Mandatory for ID Check products
     *
     * @pattern  ^(?:[0-3]\d-[01]\d-[12]\d{3})$
     *
     * @example  05-07-2019
     *
     * @var string|null $IDExpiration
     *
     * @since    1.0.0
     */
    protected $IDExpiration;

    /**
     * Document number of the ID document
     * Mandatory for ID Check products
     *
     * @pattern ^.{0,20}$
     *
     * @example 4261103214
     *
     * @var string|null $IDNumber
     *
     * @since   1.0.0
     */
    protected $IDNumber;

    /**
     * Type of the ID document.
     * Mandatory for ID Check products.
     *
     * @pattern ^\d{2}$
     *
     * @example 02
     *
     * @var string|null $IDType
     *
     * @since   1.0.0
     */
    protected $IDType;

    /**
     * Product code
     *
     * @pattern ^\d{4}$
     *
     * @example 3153
     *
     * @var string|null $productCodeCollect
     *
     * @var string|null $productCode
     *
     * @since   2.0.0
     */
    protected $productCode;

    /**
     * Second product code of a shipment
     *
     * @pattern ^\d{4}$
     *
     * @example 3153
     *
     * @var string|null $productCodeCollect
     *
     * @since   1.0.0
     */
    protected $productCodeCollect;

    /**
     * Product code of the shipment
     *
     * @pattern ^\d{4}$
     *
     * @example 3085
     *
     * @var string|null $productCodeDelivery
     *
     * @since   1.0.0
     */
    protected $productCodeDelivery;

    /**
     * Product description
     *
     * @pattern ^.{0,1000}$
     *
     * @example Standaardzending
     *
     * @var string|null
     *
     * @since   2.0.0
     */
    protected $productDescription;

    /**
     * Product options for the shipment, mandatory for certain products, see the Products page of this webservice
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @var ProductOption[]|null $productOptions
     *
     * @since   1.0.0
     */
    protected $productOptions;

    /**
     * Date of birth
     * Mandatory for Age check products
     *
     * @pattern  ^(?:[0-3]\d-[01]\d-[12]\d{3})$
     *
     * @example  01-01-1970
     *
     * @var string|null $receiverDateOfBirth
     *
     * @since    1.0.0
     */
    protected $receiverDateOfBirth;

    /**
     * Your own reference of the shipment. Mandatory for Extra@Home shipments; for E@H this is used to create your order number, so this should be unique for each request.
     *
     * @pattern ^.{0,35}$
     *
     * @example 2016014567
     *
     * @var string|null $reference
     *
     * @since   1.0.0
     */
    protected $reference;

    /**
     * Additional reference of the collect order of the shipment.
     *
     * @pattern ^.{0,35}$
     *
     * @example 6659150
     *
     * @var string|null $referenceCollect
     *
     * @since   1.0.0
     */
    protected $referenceCollect;

    /**
     * Remark of the shipment.
     *
     * @pattern ^.{0,35}$
     *
     * @example Fragile
     *
     * @var string|null $remark
     *
     * @since   1.0.0
     */
    protected $remark;

    /**
     * Return barcode of the shipment. PostNL will provide you with a separate customer code specifically for generating the returnBarcode.
     *
     * Mandatory for Label in the Box (return label) shipments.
     *
     * @pattern ^.{11,15}$
     *
     * @example 3SABCD7762162
     *
     * @var string|null $returnBarcode
     *
     * @since   1.0.0
     */
    protected $returnBarcode;

    /**
     * Return reference of the shipment.
     *
     * @pattern ^.{0,35}$
     *
     * @example 112233
     *
     * @var string|null $returnReference
     *
     * @since   1.0.0
     */
    protected $returnReference;

    /**
     * Shipment amount
     *
     * @pattern ^\d{0,10}$
     *
     * @example 1
     *
     * @var int|null $shipmentAmount
     *
     * @since   2.0.0
     */
    protected $shipmentAmount;

    /**
     * Shipment counter
     *
     * @pattern ^\d{0,10}$
     *
     * @example 1
     *
     * @var int|null $shipmentCounter
     *
     * @since   2.0.0
     */
    protected $shipmentCounter;

    /**
     * Event
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @var Event[]|null
     *
     * @since   2.0.0
     */
    protected $event;

    /**
     * Status
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @var Status|null
     *
     * @since   2.0.0
     */
    protected $status;

    /**
     * Old status
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @var OldStatus[]|null
     *
     * @since   2.0.0
     */
    protected $oldStatus;

    /**
     * Labels
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @var Label[]|null $labels
     *
     * @since   2.0.0
     */
    protected $labels;

    /**
     * Shipment constructor.
     *
     * @param Address[]|null       $addresses
     * @param array|null           $amounts
     * @param string|null          $barcode
     * @param Contact[]|null       $contacts
     * @param string|null          $content
     * @param string|null          $collectionTimeStampEnd
     * @param string|null          $collectionTimeStampStart
     * @param string|null          $costCenter
     * @param string|null          $customerOrderNumber
     * @param Customs|null         $customs
     * @param string|null          $deliveryAddress
     * @param string|null          $deliveryDate
     * @param Dimension|null       $dimension
     * @param string|null          $downPartnerBarcode
     * @param string|null          $downPartnerId
     * @param string|null          $downPartnerLocation
     * @param Group[]|null         $groups
     * @param string|null          $idExpiration
     * @param string|null          $idNumber
     * @param string|null          $idType
     * @param string|null          $productCodeCollect
     * @param string|null          $productCodeDelivery
     * @param ProductOption[]|null $productOptions
     * @param string|null          $receiverDateOfBirth
     * @param string|null          $reference
     * @param string|null          $referenceCollect
     * @param string|null          $remark
     * @param string|null          $returnBarcode
     * @param string|null          $returnReference
     *
     * @throws InvalidArgumentException
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     */
    public function __construct(?array $addresses = null, ?array $amounts = null, ?string $barcode = null, ?array $contacts = null, ?string $content = null, ?string $collectionTimeStampEnd = null, ?string $collectionTimeStampStart = null, ?string $costCenter = null, ?string $customerOrderNumber = null, ?Customs $customs = null, ?string $deliveryAddress = null, ?string $deliveryDate = null, ?Dimension $dimension = null, ?string $downPartnerBarcode = null, ?string $downPartnerId = null, ?string $downPartnerLocation = null, ?array $groups = null, ?string $idExpiration = null, ?string $idNumber = null, ?string $idType = null, ?string $productCodeCollect = null, ?string $productCodeDelivery = null, ?array $productOptions = null, ?string $receiverDateOfBirth = null, ?string $reference = null, ?string $referenceCollect = null, ?string $remark = null, ?string $returnBarcode = null, ?string $returnReference = null)
    {
        parent::__construct();

        $this->setAddresses($addresses);
        $this->setAmounts($amounts);
        $this->setBarcode($barcode);
        $this->setCollectionTimeStampEnd($collectionTimeStampEnd);
        $this->setCollectionTimeStampStart($collectionTimeStampStart);
        $this->setContacts($contacts);
        $this->setContent($content);
        $this->setCostCenter($costCenter);
        $this->setCustomerOrderNumber($customerOrderNumber);
        $this->setCustoms($customs);
        $this->setDeliveryAddress($deliveryAddress);
        $this->setDeliveryDate($deliveryDate);
        $this->setDimension($dimension);
        $this->setDownPartnerBarcode($downPartnerBarcode);
        $this->setDownPartnerID($downPartnerId);
        $this->setDownPartnerLocation($downPartnerLocation);
        $this->setGroups($groups);
        $this->setIDExpiration($idExpiration);
        $this->setIDNumber($idNumber);
        $this->setIDType($idType);
        $this->setProductCodeCollect($productCodeCollect);
        $this->setProductCodeDelivery($productCodeDelivery);
        $this->setProductOptions($productOptions);
        $this->setReceiverDateOfBirth($receiverDateOfBirth);
        $this->setReference($reference);
        $this->setReferenceCollect($referenceCollect);
        $this->setRemark($remark);
        $this->setReturnBarcode($returnBarcode);
        $this->setReturnReference($returnReference);
    }

    /**
     * Deserialize JSON
     *
     * @noinspection PhpDocRedundantThrowsInspection
     *
     * @param array $json JSON as associative array
     *
     * @return mixed
     *
     * @throws InvalidArgumentException
     *
     * @since        2.0.0
     */
    public static function jsonDeserialize(array $json)
    {
        reset($json);
        $shortClassName = key($json);
        $fullClassName = static::getFullEntityClassName($shortClassName);
        // The only key in this associate array should be the object's name
        // The value should be the object itself

        if (!$fullClassName
            || !class_exists($fullClassName)
            || !is_array($json[$shortClassName])
            || count(array_filter(array_keys($json[$shortClassName]), 'is_int')) > 0
        ) {
            // If it's not a known object or a non-associative array, just return the direct property
            return $json[$shortClassName];
        }

        $object = new static();
        foreach ($json[$shortClassName] as $key => $value) {
            if ('Labels' === $key) {
                if (isset($value['Content'])) {
                    $value = [$value];
                }
                foreach ($value as $label) {
                    $object->addLabel(Label::jsonDeserialize(['Label' => $label]));
                }
            } elseif (is_null(AbstractEntity::getFullEntityClassName($key))) {
                if (!is_array($value) || !empty($value)) {
                    $object->{"set$key"}($value);
                }
            } else {
                $object->{"set$key"}(
                    call_user_func(
                        [static::getFullEntityClassName($key), 'jsonDeserialize'],
                        [$key => $value]
                    )
                );
            }
        }

        return $object;
    }

    /**
     * Get addresses
     *
     * @return Address[]|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$addresses
     */
    public function getAddresses(): ?array
    {
        return $this->addresses;
    }

    /**
     * Set addresses
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @param Address[]|null $addresses
     *
     * @return static
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$addresses
     */
    public function setAddresses(?array $addresses): Shipment
    {
        $this->addresses = $addresses;

        return $this;
    }

    /**
     * Get amounts
     *
     * @return Amount[]|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$amounts
     */
    public function getAmounts(): ?array
    {
        return $this->amounts;
    }

    /**
     * Set amounts
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @param Amount[]|null $amounts
     *
     * @return static
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$amounts
     */
    public function setAmounts(?array $amounts): Shipment
    {
        $this->amounts = $amounts;

        return $this;
    }

    /**
     * Get barcode
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$barcode
     */
    public function getBarcode(): ?string
    {
        return $this->barcode;
    }

    /**
     * Set barcode
     *
     * @pattern ^.{1,35}$
     *
     * @example 3SDEVC2016112104
     *
     * @param string|null $barcode
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$barcode
     */
    public function setBarcode(?string $barcode): Shipment
    {
        $this->barcode = ValidateAndFix::barcode($barcode);

        return $this;
    }

    /**
     * Get coding text
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$codingText
     */
    public function getCodingText(): ?string
    {
        return $this->codingText;
    }

    /**
     * Set coding text
     *
     * @pattern ^.{0,35}$
     *
     * @example #2426A3A#03#0306#
     *
     * @param string|null $codingText
     *
     * @return static
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$codingText
     *
     * @throws InvalidArgumentException
     */
    public function setCodingText(?string $codingText): Shipment
    {
        $this->codingText = ValidateAndFix::genericString($codingText);

        return $this;
    }

    /**
     * Get collection timestamp end
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$collectionTimeStampEnd
     */
    public function getCollectionTimeStampEnd(): ?string
    {
        return $this->collectionTimeStampEnd;
    }

    /**
     * Set collection timestamp end
     *
     * @pattern ^(?:0[1-9]|[1-2][0-9]|3[0-1])-(?:0[1-9]|1[0-2])-[0-9]{4}\s(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$
     *
     * @example 03-07-2019 17:00:00
     *
     * @param string|null $collectionTimeStampEnd
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$collectionTimeStampEnd
     */
    public function setCollectionTimeStampEnd(?string $collectionTimeStampEnd): Shipment
    {
        $this->collectionTimeStampEnd = ValidateAndFix::dateTime($collectionTimeStampEnd);

        return $this;
    }

    /**
     * Get collection timestamp start
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$collectionTimeStampStart
     */
    public function getCollectionTimeStampStart(): ?string
    {
        return $this->collectionTimeStampStart;
    }

    /**
     * Set collection timestamp start
     *
     * @pattern ^(?:0[1-9]|[1-2][0-9]|3[0-1])-(?:0[1-9]|1[0-2])-[0-9]{4}\s(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$
     *
     * @example 03-07-2019 16:00:00
     *
     * @param string|null $collectionTimeStampStart
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$collectionTimeStampStart
     */
    public function setCollectionTimeStampStart(?string $collectionTimeStampStart): Shipment
    {
        $this->collectionTimeStampStart = ValidateAndFix::dateTime($collectionTimeStampStart);

        return $this;
    }

    /**
     * Get contacts
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @return Contact[]|null
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$contacts
     */
    public function getContacts(): ?array
    {
        return $this->contacts;
    }

    /**
     * Set contacts
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @param Contact[]|null $contacts
     *
     * @return static
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$contacts
     */
    public function setContacts(?array $contacts): Shipment
    {
        $this->contacts = $contacts;

        return $this;
    }

    /**
     * Get content
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @return string|null
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$content
     */
    public function getContent(): ?string
    {
        return $this->content;
    }

    /**
     * Set content
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @param string|null $content
     *
     * @return static
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$content
     */
    public function setContent(?string $content): Shipment
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get cost center
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$costCenter
     */
    public function getCostCenter(): ?string
    {
        return $this->costCenter;
    }

    /**
     * Set cost center
     *
     * @pattern ^.{0,35}$
     *
     * @example SX-GT-66
     *
     * @param string|null $costCenter
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$costCenter
     */
    public function setCostCenter(?string $costCenter): Shipment
    {
        $this->costCenter = ValidateAndFix::genericString($costCenter);

        return $this;
    }

    /**
     * Get customer order number
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$customerOrderNumber
     */
    public function getCustomerOrderNumber(): ?string
    {
        return $this->customerOrderNumber;
    }

    /**
     * Set customer order number
     *
     * @pattern ^.{0,35}$
     *
     * @example 8689242390
     *
     * @param string|null $customerOrderNumber
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$customerOrderNumber
     */
    public function setCustomerOrderNumber(?string $customerOrderNumber): Shipment
    {
        $this->customerOrderNumber = ValidateAndFix::genericString($customerOrderNumber);

        return $this;
    }

    /**
     * Get customs
     *
     * @return Customs|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$customs
     */
    public function getCustoms(): ?Customs
    {
        return $this->customs;
    }

    /**
     * Set customs
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @param Customs|null $customs
     *
     * @return static
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$customs
     */
    public function setCustoms(?Customs $customs): Shipment
    {
        $this->customs = $customs;

        return $this;
    }

    /**
     * Get delivery address type
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$deliveryAddress
     */
    public function getDeliveryAddress(): ?string
    {
        return $this->deliveryAddress;
    }

    /**
     * Set delivery address type
     *
     * @pattern pattern: ^\d{2}$
     *
     * @example 09
     *
     * @param string|null $deliveryAddress
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$deliveryAddress
     */
    public function setDeliveryAddress(?string $deliveryAddress): Shipment
    {
        $this->deliveryAddress = ValidateAndFix::numericType($deliveryAddress);

        return $this;
    }

    /**
     * Get delivery timestamp start
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$deliveryTimeStampStart
     */
    public function getDeliveryTimeStampStart(): ?string
    {
        return $this->deliveryTimeStampStart;
    }

    /**
     * Set delivery timestamp start
     *
     * @pattern ^(?:[0-3]\d-[01]\d-[12]\d{3}\s+)[0-2]\d:[0-5]\d(?:[0-5]\d)$
     *
     * @example 03-07-2019 14:30:00
     *
     * @param string|null $deliveryTimeStampStart
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$deliveryTimeStampStart
     */
    public function setDeliveryTimeStampStart(?string $deliveryTimeStampStart): Shipment
    {
        $this->deliveryTimeStampStart = ValidateAndFix::time($deliveryTimeStampStart);

        return $this;
    }

    /**
     * Get delivery timestamp end
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$deliveryTimeStampEnd
     */
    public function getDeliveryTimeStampEnd(): ?string
    {
        return $this->deliveryTimeStampEnd;
    }

    /**
     * Set delivery timestamp end
     *
     * @pattern ^(?:[0-3]\d-[01]\d-[12]\d{3}\s+)[0-2]\d:[0-5]\d(?:[0-5]\d)$
     *
     * @example 03-07-2019 16:30:00
     *
     * @param string|null $deliveryTimeStampEnd
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$deliveryTimeStampEnd
     */
    public function setDeliveryTimeStampEnd(?string $deliveryTimeStampEnd): Shipment
    {
        $this->deliveryTimeStampEnd = ValidateAndFix::time($deliveryTimeStampEnd);

        return $this;
    }

    /**
     * Get delivery date
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$deliveryDate
     */
    public function getDeliveryDate(): ?string
    {
        return $this->deliveryDate;
    }

    /**
     * Set delivery date
     *
     * @pattern ^(?:0[1-9]|[1-2][0-9]|3[0-1])-(?:0[1-9]|1[0-2])-[0-9]{4}\s(?:2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]$
     *
     * @example 03-07-2019 14:00:00
     *
     * @param string|null $deliveryDate
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$deliveryDate
     */
    public function setDeliveryDate(?string $deliveryDate): Shipment
    {
        $this->deliveryDate = ValidateAndFix::dateTime($deliveryDate);

        return $this;
    }

    /**
     * Get dimension
     *
     * @return Dimension|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$dimension
     */
    public function getDimension(): ?Dimension
    {
        return $this->dimension;
    }

    /**
     * Set dimension
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @param Dimension|null $dimension
     *
     * @return static
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$dimension
     */
    public function setDimension(?Dimension $dimension): Shipment
    {
        $this->dimension = $dimension;

        return $this;
    }

    /**
     * Get down partner barcode
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$downPartnerBarcode
     */
    public function getDownPartnerBarcode(): ?string
    {
        return $this->downPartnerBarcode;
    }

    /**
     * Set down partner barcode
     *
     * @pattern ^.{0,35}$
     *
     * @example CD123456785NL
     *
     * @param string|null $downPartnerBarcode
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$downPartnerBarcode
     */
    public function setDownPartnerBarcode(?string $downPartnerBarcode): Shipment
    {
        $this->downPartnerBarcode = ValidateAndFix::genericString($downPartnerBarcode);

        return $this;
    }

    /**
     * Get down partner ID
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$downPartnerID
     */
    public function getDownPartnerID(): ?string
    {
        return $this->downPartnerID;
    }

    /**
     * Set down partner ID
     *
     * @pattern ^.{0,35}$
     *
     * @example LD-01
     *
     * @param string|null $downPartnerID
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$downPartnerID
     */
    public function setDownPartnerID(?string $downPartnerID): Shipment
    {
        $this->downPartnerID = ValidateAndFix::genericString($downPartnerID);

        return $this;
    }

    /**
     * Get down partner location
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$downPartnerLocation
     */
    public function getDownPartnerLocation(): ?string
    {
        return $this->downPartnerLocation;
    }

    /**
     * Set down partner location
     *
     * @pattern ^.{0,10}$
     *
     * @example BE0Q82
     *
     * @param string|null $downPartnerLocation
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$downPartnerLocation
     */
    public function setDownPartnerLocation(?string $downPartnerLocation): Shipment
    {
        $this->downPartnerLocation = ValidateAndFix::genericString($downPartnerLocation);

        return $this;
    }

    /**
     * Get groups
     *
     * @return Group[]|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$groups
     */
    public function getGroups(): ?array
    {
        return $this->groups;
    }

    /**
     * Set groups
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @param Group[]|null $groups
     *
     * @return static
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$groups
     */
    public function setGroups(?array $groups): Shipment
    {
        $this->groups = $groups;

        return $this;
    }

    /**
     * Get ID expiration date
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$IDExpiration
     */
    public function getIDExpiration(): ?string
    {
        return $this->IDExpiration;
    }

    /**
     * Set ID expiration date
     *
     * @pattern  ^(?:[0-3]\d-[01]\d-[12]\d{3})$
     *
     * @example  05-07-2019
     *
     * @param string|null $IDExpiration
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since    1.0.0
     * @since    2.0.0 Strict typing
     *
     * @see      Shipment::$IDExpiration
     */
    public function setIDExpiration(?string $IDExpiration): Shipment
    {
        $this->IDExpiration = ValidateAndFix::date($IDExpiration);

        return $this;
    }

    /**
     * Get ID number
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$IDNumber
     */
    public function getIDNumber(): ?string
    {
        return $this->IDNumber;
    }

    /**
     * Set ID number
     *
     * @pattern ^.{0,20}$
     *
     * @example 4261103214
     *
     * @param string|null $IDNumber
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$IDNumber
     */
    public function setIDNumber(?string $IDNumber): Shipment
    {
        $this->IDNumber = ValidateAndFix::genericString($IDNumber, 20);

        return $this;
    }

    /**
     * Get ID type
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$IDType
     */
    public function getIDType(): ?string
    {
        return $this->IDType;
    }

    /**
     * Set ID type
     *
     * @pattern ^\d{2}$
     *
     * @example 02
     *
     * @param string|null $IDType
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$IDType
     */
    public function setIDType(?string $IDType): Shipment
    {
        $this->IDType = ValidateAndFix::numericType($IDType);

        return $this;
    }

    /**
     * Get product code collect
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$productCodeCollect
     */
    public function getProductCodeCollect(): ?string
    {
        return $this->productCodeCollect;
    }

    /**
     * Set product code collect
     *
     * @pattern ^\d{4}$
     *
     * @example 3153
     *
     * @param string|null $productCodeCollect
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$productCodeCollect
     */
    public function setProductCodeCollect(?string $productCodeCollect): Shipment
    {
        $this->productCodeCollect = ValidateAndFix::productCode($productCodeCollect);

        return $this;
    }

    /**
     * Get product code delivery
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$productCodeDelivery
     */
    public function getProductCodeDelivery(): ?string
    {
        return $this->productCodeDelivery;
    }

    /**
     * Set product code delivery
     *
     * @pattern ^\d{4}$
     *
     * @example 3085
     *
     * @param string|null $productCodeDelivery
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$productCodeDelivery
     */
    public function setProductCodeDelivery(?string $productCodeDelivery): Shipment
    {
        $this->productCodeDelivery = ValidateAndFix::productCode($productCodeDelivery);

        return $this;
    }

    /**
     * Get product options
     *
     * @return ProductOption[]|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$productOptions
     */
    public function getProductOptions(): ?array
    {
        return $this->productOptions;
    }

    /**
     * Set product options
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @param ProductOption[]|null $productOptions
     *
     * @return static
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$productOptions
     */
    public function setProductOptions(?array $productOptions): Shipment
    {
        $this->productOptions = $productOptions;

        return $this;
    }

    /**
     * Get receiver date of birth
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$receiverDateOfBirth
     */
    public function getReceiverDateOfBirth(): ?string
    {
        return $this->receiverDateOfBirth;
    }

    /**
     * Set receiver date of birth
     *
     * @pattern  ^(?:[0-3]\d-[01]\d-[12]\d{3})$
     *
     * @example  01-01-1970
     *
     * @param string|null $receiverDateOfBirth
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since    1.0.0
     * @since    2.0.0 Strict typing
     *
     * @see      Shipment::$receiverDateOfBirth
     */
    public function setReceiverDateOfBirth(?string $receiverDateOfBirth): Shipment
    {
        $this->receiverDateOfBirth = ValidateAndFix::date($receiverDateOfBirth);

        return $this;
    }

    /**
     * Get reference
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$reference
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Set reference
     *
     * @pattern ^.{0,35}$
     *
     * @example 2016014567
     *
     * @param string|null $reference
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$reference
     */
    public function setReference(?string $reference): Shipment
    {
        $this->reference = ValidateAndFix::genericString($reference);

        return $this;
    }

    /**
     * Get reference collect
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$referenceCollect
     */
    public function getReferenceCollect(): ?string
    {
        return $this->referenceCollect;
    }

    /**
     * Set reference collect
     *
     * @pattern ^.{0,35}$
     *
     * @example 6659150
     *
     * @param string|null $referenceCollect
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$referenceCollect
     */
    public function setReferenceCollect(?string $referenceCollect): Shipment
    {
        $this->referenceCollect = ValidateAndFix::genericString($referenceCollect);

        return $this;
    }

    /**
     * Get remark
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$remark
     */
    public function getRemark(): ?string
    {
        return $this->remark;
    }

    /**
     * Set remark
     *
     * @pattern ^.{0,35}$
     *
     * @example Fragile
     *
     * @param string|null $remark
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$remark
     */
    public function setRemark(?string $remark): Shipment
    {
        $this->remark = ValidateAndFix::genericString($remark);

        return $this;
    }

    /**
     * Set remark
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$remark
     */
    public function getReturnBarcode(): ?string
    {
        return $this->returnBarcode;
    }

    /**
     * Set return barcode
     *
     * @pattern ^.{11,15}$
     *
     * @example 3SABCD7762162
     *
     * @param string|null $returnBarcode
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$returnBarcode
     */
    public function setReturnBarcode(?string $returnBarcode): Shipment
    {
        $this->returnBarcode = ValidateAndFix::barcode($returnBarcode);

        return $this;
    }

    /**
     * Get return reference
     *
     * @return string|null
     *
     * @since 1.0.0
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$returnReference
     */
    public function getReturnReference(): ?string
    {
        return $this->returnReference;
    }

    /**
     * Set return reference
     *
     * @pattern ^.{0,35}$
     *
     * @example 112233
     *
     * @param string|null $returnReference
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   1.0.0
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$returnReference
     */
    public function setReturnReference(?string $returnReference): Shipment
    {
        $this->returnReference = ValidateAndFix::genericString($returnReference);

        return $this;
    }

    /**
     * Get main barcode
     *
     * @return string|null
     *
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$barcode
     */
    public function getMainBarcode(): ?string
    {
        return $this->mainBarcode;
    }

    /**
     * Set main barcode
     *
     * @pattern ^{0,95}$
     *
     * @example 3SDEVC2309482387
     *
     * @param string|null $mainBarcode
     *
     * @return static
     *
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$barcode
     */
    public function setMainBarcode(?string $mainBarcode): Shipment
    {
        $this->mainBarcode = $mainBarcode;

        return $this;
    }

    /**
     * Get shipment amount
     *
     * @return int|null
     *
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$shipmentAmount
     */
    public function getShipmentAmount(): ?int
    {
        return $this->shipmentAmount;
    }

    /**
     * Set shipment amount
     *
     * @pattern ^\d{0,10}$
     *
     * @example 1
     *
     * @param int|float|string|null $shipmentAmount
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$shipmentAmount
     */
    public function setShipmentAmount($shipmentAmount): Shipment
    {
        $this->shipmentAmount = ValidateAndFix::integer($shipmentAmount);

        return $this;
    }

    /**
     * Get shipment counter
     *
     * @return int|null
     *
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$shipmentCounter
     */
    public function getShipmentCounter(): ?int
    {
        return $this->shipmentCounter;
    }

    /**
     * Set shipment counter
     *
     * @pattern ^\d{0,10}$
     *
     * @example 1
     *
     * @param int|float|string|null $shipmentCounter
     *
     * @return static
     *
     * @throws InvalidArgumentException
     *
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$shipmentCounter
     */
    public function setShipmentCounter($shipmentCounter): Shipment
    {
        $this->shipmentCounter = ValidateAndFix::integer($shipmentCounter);

        return $this;
    }

    /**
     * Get customer
     *
     * @return Customer|null
     *
     * @since 2.0.0 Strict typing
     *
     * @see   Customer
     */
    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    /**
     * Set customer
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @param Customer|null $customer
     *
     * @return static
     *
     * @since   2.0.0 Strict typing
     *
     * @see     Customer
     */
    public function setCustomer(?Customer $customer): Shipment
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * Get product code
     *
     * @return string|null
     *
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$productCode
     */
    public function getProductCode(): ?string
    {
        return $this->productCode;
    }

    /**
     * Set product code
     *
     * @pattern ^.{0,35}$
     *
     * @example 003085
     *
     * @param string|null $productCode
     *
     * @return static
     *
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$productCode
     */
    public function setProductCode(?string $productCode): Shipment
    {
        $this->productCode = $productCode;

        return $this;
    }

    /**
     * Get product description
     *
     * @return string|null
     *
     * @since 2.0.0 Strict typing
     *
     * @see   Shipment::$productDescription
     */
    public function getProductDescription(): ?string
    {
        return $this->productDescription;
    }

    /**
     * Set product description
     *
     * @pattern ^.{0,95}$
     *
     * @example Standaardzending
     *
     * @param string|null $productDescription
     *
     * @return static
     *
     * @since   2.0.0 Strict typing
     *
     * @see     Shipment::$productDescription
     */
    public function setProductDescription(?string $productDescription): Shipment
    {
        $this->productDescription = $productDescription;

        return $this;
    }

    /**
     * Get addresses
     *
     * @return Address[]|null
     *
     * @since 2.0.0 Strict typing
     *
     * @see   Address
     */
    public function getAddress(): ?array
    {
        return $this->address;
    }

    /**
     * Set addresses
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @param Address[]|null $address
     *
     * @return static
     *
     * @since   2.0.0 Strict typing
     *
     * @see     Address
     */
    public function setAddress(?array $address): Shipment
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Get events
     *
     * @return Event[]|null
     *
     * @since 2.0.0 Strict typing
     *
     * @see   Event
     */
    public function getEvent(): ?array
    {
        return $this->event;
    }

    /**
     * Set events
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @param Event[]|null $event
     *
     * @return static
     *
     * @since   2.0.0 Strict typing
     *
     * @see     Event
     */
    public function setEvent(?array $event): Shipment
    {
        $this->event = $event;

        return $this;
    }

    /**
     * Get status
     *
     * @return Status|null
     *
     * @since 2.0.0 Strict typing
     *
     * @see   Status
     */
    public function getStatus(): ?Status
    {
        return $this->status;
    }

    /**
     * Set status
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @param Status|null $status
     *
     * @return static
     *
     * @since   2.0.0 Strict typing
     *
     * @see     Status
     */
    public function setStatus(?Status $status): Shipment
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get old statuses
     *
     * @return OldStatus[]|null
     *
     * @since 2.0.0 Strict typing
     *
     * @see   OldStatus
     */
    public function getOldStatus(): ?array
    {
        return $this->oldStatus;
    }

    /**
     * Set old status
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @param OldStatus[]|null $oldStatus
     *
     * @return static
     *
     * @since   2.0.0 Strict typing
     *
     * @see     OldStatus
     */
    public function setOldStatus(?array $oldStatus): Shipment
    {
        $this->oldStatus = $oldStatus;

        return $this;
    }

    /**
     * Get labels
     *
     * @return Label[]|null
     *
     * @since 2.0.0 Strict typing
     *
     * @see   Label
     */
    public function getLabels(): ?array
    {
        return $this->labels;
    }

    /**
     * Add label
     *
     * @param Label $label
     *
     * @return Shipment
     *
     * @since 2.0.0
     *
     * @see   Label
     *
     * @see   Label
     */
    public function addLabel(Label $label): Shipment
    {
        $this->labels[] = $label;

        return $this;
    }

    /**
     * Set labels
     *
     * @pattern N/A
     *
     * @example N/A
     *
     * @param Label[]|null $labels
     *
     * @return static
     *
     * @since   2.0.0 Strict typing
     *
     * @see     Label
     */
    public function setLabels(?array $labels): Shipment
    {
        $this->labels = $labels;

        return $this;
    }
}
