HTTP/1.1 200 OK
Access-Control-Allow-Headers: origin, x-requested-with, accept, apikey, Content-Type
Access-Control-Allow-Methods: GET, POST
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 3628800
Cache-Control: private, max-age=0
Content-Type: application/json;charset=UTF-8
Date: Wed, 31 Mar 2021 00:24:44 GMT
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Robots-Tag: noindex
X-XSS-Protection: 1; mode=block
Connection: keep-alive

{"ReasonNoTimeframes":{"ReasonNoTimeframe":[{"Code":98,"Date":"29-03-2021","Description":"Gevraagde datum ligt in het verleden","Options":{"string":"Daytime"}},{"Code":98,"Date":"30-03-2021","Description":"Gevraagde datum ligt in het verleden","Options":{"string":"Daytime"}}]},"Timeframes":{"Timeframe":[{"Date":"31-03-2021","Timeframes":{"TimeframeTimeFrame":{"From":"10:00:00","Options":{"string":"Daytime"},"To":"12:30:00"}}},{"Date":"01-04-2021","Timeframes":{"TimeframeTimeFrame":{"From":"09:45:00","Options":{"string":"Daytime"},"To":"12:15:00"}}},{"Date":"02-04-2021","Timeframes":{"TimeframeTimeFrame":{"From":"09:45:00","Options":{"string":"Daytime"},"To":"12:15:00"}}}]}}
